config/routes.rb
Rails.application.routes.draw do
  root 'index#index'
  #Rutas para usuarios.
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :meals do
    collection do
      get 'categories'
      get 'recipes/:category', action: 'recipes_by_category', as: 'recipes_by_category'
    end
  end
  #Para mostrar 5 recetas aleatorias
  get 'aleatorio/recetas_aleatorias', to: 'aleatorio#recetas_aleatorias', as: 'aleatorias'
  #Para buscar recetas
  get 'buscar', to: 'busqueda#buscar', as: 'buscar'
  #Para mostrar el detalle de una receta.
  get 'mostrar_detalles/detalles', as: 'show_details'

  #Para listar las recetas que el usuario haya guardado.
  get 'mi_lista/lista', as: 'mi_lista'

  #Para realizar la peticion post para guardar y eliminar un item en lista.
  post 'mi_lista/create', as: 'guardar_item'
  post 'mi_lista/delete', to: 'mi_lista#delete', via: :delete, as: 'eliminar_item'

  #Eliminar desde al vista de la lista de cada usuario.
  delete 'mi_lista/delete_from_my_list', to: 'mi_lista#delete_from_my_list', via: :delete, as: 'eliminar_item_from'

  #Para realizar la peticion de descargar el archivo PDF.
  get 'pdfnizator/receta', as: 'pdfizador'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/mi_lista_controller.rb
class MiListaController < ApplicationController
  before_action :authenticate_user!

  def lista
    #Listar las recetas que ha agregado el usuario.
    @user_list = current_user.user_list.order(:recipe_name)
  end

  #Crear item en lista.
  def create
    item = UserList.new(recipe_params)

    #Guarda un item a la lista.
    if item.save
      redirect_to show_details_path(id: item.idMeal)
      flash[:notice] = "Se ha agregado #{item.recipe_name} a su lista con exito."
    else
      redirect_to show_details_path(id: item.idMeal)
      flash[:alert] = "No se ha podido guardar #{item.recipe_name} en lista."
    end
  end

  #Eliminar item en lista.
  def delete
    item = UserList.find_by(user_id: current_user.id, idMeal: params[:idMeal])

    #Eliminar un item a la lista.
    if item.delete
      redirect_to show_details_path(id: item.idMeal)
      flash[:notice] = "Se ha eliminado #{item.recipe_name} de su lista con exito."
    else
      redirect_to show_details_path(id: item.idMeal)
      flash[:alert] = "No se ha podido eliminar #{item.recipe_name} de la lista."
    end
  end

  def delete_from_my_list
    item = UserList.find_by(user_id: current_user.id, idMeal: params[:idMeal])

    #Eliminar un item a la lista.
    if item.delete
      redirect_to mi_lista_path
      flash[:notice] = "Se ha eliminado #{item.recipe_name} de su lista con exito."
    else
      redirect_to mi_lista_path
      flash[:alert] = "No se ha podido eliminar #{item.recipe_name} de la lista."
    end
  end

  private

  #Que parametros permitir.
  def recipe_params
    params.require(:user_list).permit(:user_id, :idMeal, :recipe_name, :imgPreview)
  end
end

app/helpers/mi_lista_helper.rb
module MiListaHelper
end

app/views/mi_lista/lista.html.erb
<% provide(:titulo, "Mi lista") %>
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="lista.css">
</head>
<body>
    <div class="centered-container">
        <h1>Mi Lista</h1>
        <% if not @user_list.empty? %>
            <table>
                <% @user_list.each do |item| %>
                    <tr>
                        <td><%= image_tag(item.imgPreview) %></td>
                        <td><%= item.recipe_name %></td>
                        <td><%= button_to "Detalles", show_details_path, params: {id: item.idMeal}, method: :get %></td>
                        <td><%= button_to 'Eliminar', eliminar_item_from_path(idMeal: item.idMeal), data: { turbo_method: :delete, turbo_confirm: '¿seguro?' }, method: :delete %></td>
                        <td><%= button_to 'Descargar receta', pdfizador_path(format: :pdf), params: {id: item.idMeal}, method: :get, download: true %></td>
                    </tr>
                <% end %>
            </table>
        <% else %>
            <h1>Esta algo desierto por estos lares...</h1>
        <% end %>
    </div>
</body>
</html>