config/routes.rb
Rails.application.routes.draw do
  root 'index#index'
  #Rutas para usuarios.
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :meals do
    collection do
      get 'categories'
      get 'recipes/:category', action: 'recipes_by_category', as: 'recipes_by_category'
    end
  end
  #Para mostrar 5 recetas aleatorias
  get 'aleatorio/recetas_aleatorias', to: 'aleatorio#recetas_aleatorias', as: 'aleatorias'
  #Para buscar recetas
  get 'buscar', to: 'busqueda#buscar', as: 'buscar'
  #Para mostrar el detalle de una receta.
  get 'mostrar_detalles/detalles', as: 'show_details'

  #Para listar las recetas que el usuario haya guardado.
  get 'mi_lista/lista', as: 'mi_lista'

  #Para realizar la peticion post para guardar y eliminar un item en lista.
  post 'mi_lista/create', as: 'guardar_item'
  post 'mi_lista/delete', to: 'mi_lista#delete', via: :delete, as: 'eliminar_item'

  #Eliminar desde al vista de la lista de cada usuario.
  delete 'mi_lista/delete_from_my_list', to: 'mi_lista#delete_from_my_list', via: :delete, as: 'eliminar_item_from'

  #Para realizar la peticion de descargar el archivo PDF.
  get 'pdfnizator/receta', as: 'pdfizador'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/partials/_navbar.html.erb
<div id="navbar" class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">

  
    <button  class="btn navbar-toggler navbar-left" id="sidebar-toggle" onclick="mostrarSideBar()">
      <i class="fa-solid fa-bars"></i> <!-- Utiliza la clase de Font Awesome para el ícono de Facebook -->
    </button>

    <%= link_to "Inicio", root_path, class: "btn btn-link nav-link" %>
    <%= link_to "Categorias", categories_meals_path, class: "btn btn-link nav-link" %>
    <%= link_to "Recetas aleatorias", aleatorias_path, class: "btn btn-link nav-link" %>

    <%= form_tag(buscar_path, method: :get, class: "navbar-form navbar-right") do %>
      <div class="form-group">
        <%= text_field_tag :query, params[:query], class: "form-control", placeholder: "Buscar recetas..." %>
      </div>
      <%= submit_tag "Buscar", class: "btn btn-light nav-link" %>
    <% end %>

  </div>
</div>

<script>

// para activar el sidebar
function mostrarSideBar() {
  document.getElementById('sidebar').classList.toggle('active');
}

</script>

app/views/partials/_sidebar.html.erb
<aside id="sidebar">
  <ul>
    <% if signed_in? %>
      <li><%= link_to "Mi Lista", mi_lista_path %></li>
      <li><%= link_to "Salir", destroy_user_session_path, data: { turbo_method: :delete, turbo_confirm: '¿Está seguro?' } %></li>
      <li><%= link_to "Editar Cuenta", edit_user_registration_path %></li>
      <li><%= link_to "Eliminar cuenta", registration_path(current_user), data: { turbo_method: :delete, turbo_confirm: "¿Está seguro que desea eliminar la cuenta?" } %></li>
    <% else %>
    
    <li>
  <%= link_to new_user_registration_path do %>
    <i class="fa-solid fa-user"></i>      Registrarse
  <% end %>
    </li>
      <li><%= link_to "Ingresar", new_user_session_path %></li>
    <% end %>
  </ul>
</aside>