config/routes.rb
Rails.application.routes.draw do
  root 'index#index'
  #Rutas para usuarios.
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :meals do
    collection do
      get 'categories'
      get 'recipes/:category', action: 'recipes_by_category', as: 'recipes_by_category'
    end
  end
  #Para mostrar 5 recetas aleatorias
  get 'aleatorio/recetas_aleatorias', to: 'aleatorio#recetas_aleatorias', as: 'aleatorias'
  #Para buscar recetas
  get 'buscar', to: 'busqueda#buscar', as: 'buscar'
  #Para mostrar el detalle de una receta.
  get 'mostrar_detalles/detalles', as: 'show_details'

  #Para listar las recetas que el usuario haya guardado.
  get 'mi_lista/lista', as: 'mi_lista'

  #Para realizar la peticion post para guardar y eliminar un item en lista.
  post 'mi_lista/create', as: 'guardar_item'
  post 'mi_lista/delete', to: 'mi_lista#delete', via: :delete, as: 'eliminar_item'

  #Eliminar desde al vista de la lista de cada usuario.
  delete 'mi_lista/delete_from_my_list', to: 'mi_lista#delete_from_my_list', via: :delete, as: 'eliminar_item_from'

  #Para realizar la peticion de descargar el archivo PDF.
  get 'pdfnizator/receta', as: 'pdfizador'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  require 'net/http'
  require 'json'

  def categories
    # Usa la caché para almacenar/recuperar los resultados
    @categorias = Rails.cache.fetch("Categorias", expires_in: 1.hour) do

      # Construye la URL de la API para obtener recetas por categoría
      api_url = "https://www.themealdb.com/api/json/v1/1/categories.php"

      # Realiza la solicitud a la API
      response = Net::HTTP.get(URI(api_url))

      if not response.empty?
        # Convierte la respuesta JSON en un objeto Ruby
        JSON.parse(response)['categories']
      else
        @categorias = ""
      end
    end
  end

  def recipes_by_category
    category = params[:category]
    # Usa la caché para almacenar/recuperar los resultados
    @recipes = Rails.cache.fetch("recipes_by_category_#{category}", expires_in: 1.hour) do
      # Construye la URL de la API para obtener recetas por categoría
      api_url = "https://www.themealdb.com/api/json/v1/1/filter.php?c=#{category}"
      @name = category

      # Realiza la solicitud a la API
      response = Net::HTTP.get(URI(api_url))

      if not response.empty?
        # Convierte la respuesta JSON en un objeto Ruby
        JSON.parse(response)['meals']
      else
        @recipes = ""
      end
    end
  end
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/views/meals/categories.html.erb
<% provide(:titulo, "Categorias") %>
<div class="categorias-header">
  <h1 id="categorias">Categorías de Recetas</h1>
</div>

<% if not @categorias.empty? %>
  <ul class="categorias-list">
    <% @categorias.each do |data| %>
      <li class="categorias-item">
        <h2><%= data["strCategory"] %></h2>
        <div class="categoria-content">
          <%= image_tag(data["strCategoryThumb"], class: "categoria-imagen") %>
          <div class="categoria-info">
            <%= simple_format(data["strCategoryDescription"]).gsub(/\n+/, "<br>").html_safe %>
            <%= link_to "Ver todas las recetas", recipes_by_category_meals_path(category: data["strCategory"]), class: "gray-button" %>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
<% else %>
  <h1>Ups. algo ha ido mal...</h1>
<% end %>

app/views/meals/recipes_by_category.html.erb
<% provide(:titulo, @name) %>
<div id="recipe-title" class="text-center"> 
  <h1>Todas las Recetas de: <%= @name %></h1>
</div>

<% if not @recipes.empty? %>
  <div class="recipe-grid"> <!-- Nuevo contenedor de la cuadrícula -->
    <% @recipes.each do |recipe| %>
      <div class="recipe-card"> <!-- Cada tarjeta de receta -->
        <%= image_tag(recipe["strMealThumb"]) %>
        <h2><%= recipe['strMeal'] %></h2>
        <%= link_to "Detalles de la receta", show_details_path(id: recipe['idMeal']), class: "gray-button" %>
      </div>
    <% end %>
  </div>
<% else %>
  <h1>Ups, algo ha ido mal</h1>
<% end %>

<%= link_to "Volver a las Categorías", categories_meals_path, class: "gray-button2" %>