config/routes.rb
Rails.application.routes.draw do
  root 'index#index'
  #Rutas para usuarios.
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :meals do
    collection do
      get 'categories'
      get 'recipes/:category', action: 'recipes_by_category', as: 'recipes_by_category'
    end
  end
  #Para mostrar 5 recetas aleatorias
  get 'aleatorio/recetas_aleatorias', to: 'aleatorio#recetas_aleatorias', as: 'aleatorias'
  #Para buscar recetas
  get 'buscar', to: 'busqueda#buscar', as: 'buscar'
  #Para mostrar el detalle de una receta.
  get 'mostrar_detalles/detalles', as: 'show_details'

  #Para listar las recetas que el usuario haya guardado.
  get 'mi_lista/lista', as: 'mi_lista'

  #Para realizar la peticion post para guardar y eliminar un item en lista.
  post 'mi_lista/create', as: 'guardar_item'
  post 'mi_lista/delete', to: 'mi_lista#delete', via: :delete, as: 'eliminar_item'

  #Eliminar desde al vista de la lista de cada usuario.
  delete 'mi_lista/delete_from_my_list', to: 'mi_lista#delete_from_my_list', via: :delete, as: 'eliminar_item_from'

  #Para realizar la peticion de descargar el archivo PDF.
  get 'pdfnizator/receta', as: 'pdfizador'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/controllers/mostrar_detalles_controller.rb
class MostrarDetallesController < ApplicationController
  require 'net/http'

  def detalles
    #Obtener la receta de la cual se quiere mostrar los detalles mediante el ID.

    id = params[:id]
    #Construir la URL.
    api_url = "https://www.themealdb.com/api/json/v1/1/lookup.php?i=#{id}"
    @ingredientesImg = "https://www.themealdb.com/images/ingredients/"

    # Realiza la solicitud a la API
    response = Net::HTTP.get(URI(api_url))

    if not response.empty?
      # Convierte la respuesta JSON en un objeto Ruby
      @recipe = JSON.parse(response)['meals']
    else
      @recipe = {}
    end

    #Verifica si el cliente ha agregado esa receta a su lista.
    if signed_in?
      @existe = UserList.exists?(user_id: current_user.id, idMeal: id)
    end
  end
end

app/helpers/mostrar_detalles_helper.rb
module MostrarDetallesHelper
end

app/views/mostrar_detalles/detalles.html.erb
<% if not @recipe.empty? %>
    <%@recipe.each do |data|%>
        <% provide(:titulo, data["strMeal"]) %>
        <h2><%= data["strMeal"] %></h2>
<img src="<%= data["strMealThumb"] %>" alt="<%= data["strMeal"] %>">
<h3>Categoria: <%= data["strCategory"] %></h3>
<h3>Origen: <%= data["strArea"] %></h3>
<table>
    <tr>
        <th>Ingredientes</th>
    </tr>
    <% for i in 1..20 %>
        <% if data["strIngredient#{i}"] != "" and data["strIngredient#{i}"] != nil %>
            <tr>
                <td><%= image_tag(@ingredientesImg + data["strIngredient#{i}"] + "-Small.png") %></td>
                <td><%= data["strIngredient#{i}"] %></td>
                <td><%= data["strMeasure#{i}"] %></td>
            </tr>
        <% else %>
            <% break %>
        <% end %>
    <% end %>
</table><br>
<h3>Instrucciones</h3>
<%#Para que muestre el texto correctamente. %>
<%= simple_format(data["strInstructions"]).gsub(/\n+/, "<br>").html_safe %><br>

<%# funcionalidad con botones de agregar y borrar, solo si se está loggeado %>

<% if signed_in? %>
    <% if @existe %>
        <div style="display: inline-block;">
            <%= button_to 'Eliminar de la lista', eliminar_item_path, params: {idMeal: data["idMeal"]}, disabled: false, data: { turbo_method: :delete, turbo_confirm: '¿Estás seguro?' } %>
        </div>
    <% else %>
        <div style="display: inline-block;">
            <%= button_to 'Añadir a lista', guardar_item_path, params: {user_list: {user_id: current_user.id, idMeal: data["idMeal"], recipe_name: data["strMeal"], imgPreview: data["strMealThumb"] + "/preview"}}, disabled: false %>
        </div>
    <% end %>
    <div style="display: inline-block;">
        <%= button_to 'Descargar receta', pdfizador_path(format: :pdf), params: {id: data["idMeal"]}, method: :get, download: true %>
    </div>
<% end %>
<% end %>
<% else %>
<h1>Ups, algo ha ido mal...</h1>
<% end %>